// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneBook.Models;

namespace PhoneBook.Migrations
{
    [DbContext(typeof(PhoneBookContext))]
    partial class PhoneBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhoneBook.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ул.Домашняя 5, кв 10",
                            Description = "Адмирал",
                            Name = "Виталий",
                            PhoneNumber = "333222",
                            SecondName = "Марисович",
                            Surname = "Попов"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул.Тульская 17, кв 102",
                            Description = "Сталевар",
                            Name = "Степан",
                            PhoneNumber = "111777",
                            SecondName = "Юрьевич",
                            Surname = "Горохов"
                        },
                        new
                        {
                            Id = 3,
                            Address = "пр.Мариинский 32, кв 6",
                            Description = "Балерина",
                            Name = "Надежда",
                            PhoneNumber = "555666",
                            SecondName = "Александровна",
                            Surname = "Ипатьева"
                        },
                        new
                        {
                            Id = 4,
                            Address = "ул.Кротовая 17, кв 15",
                            Description = "Землекоп",
                            Name = "Юрий",
                            PhoneNumber = "999345",
                            SecondName = "Павлович",
                            Surname = "Новиков"
                        },
                        new
                        {
                            Id = 5,
                            Address = "пр.Ленина 82, кв 27",
                            Description = "Египтолог",
                            Name = "Александр",
                            PhoneNumber = "322228",
                            SecondName = "Романович",
                            Surname = "Песьяков"
                        },
                        new
                        {
                            Id = 6,
                            Address = "ул.Котовская 4, кв 21",
                            Description = "Повар",
                            Name = "Татьяна",
                            PhoneNumber = "901902",
                            SecondName = "Владимировна",
                            Surname = "Шаляпина"
                        },
                        new
                        {
                            Id = 7,
                            Address = "ул.Малая Набережная 67, кв 33",
                            Description = "Рыбак",
                            Name = "Борис",
                            PhoneNumber = "678876",
                            SecondName = "Дмитриевич",
                            Surname = "Кузнецов"
                        },
                        new
                        {
                            Id = 8,
                            Address = "пр.Советов 77, кв 158",
                            Description = "Судья",
                            Name = "Анна",
                            PhoneNumber = "345678",
                            SecondName = "Владимировна",
                            Surname = "Кудряшова"
                        },
                        new
                        {
                            Id = 9,
                            Address = "пер.Лебяжий 99, кв 12",
                            Description = "Моряк",
                            Name = "Александр",
                            PhoneNumber = "807451",
                            SecondName = "Александрович",
                            Surname = "Петров"
                        },
                        new
                        {
                            Id = 10,
                            Address = "ул.Строителей 39, кв 71",
                            Description = "Бухгалтер",
                            Name = "Валерий",
                            PhoneNumber = "999050",
                            SecondName = "Вячеславович",
                            Surname = "Арзамасцев"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
